name: Fetch Google Trends Daily

on:
  schedule:
    - cron: '0 13 * * *'  # Runs daily at 5:00 AM PST
  workflow_dispatch:

jobs:
  fetch-trends:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pytrends

      - name: Run Google Trends Scraper
        run: python fetch_and_upload_google_trends.py
